### ISSUE TITLE
Update the documentation for CircleCI

### ISSUE THREAD

**Issue by yitingw3** [mathworks/matlab-circleci-orb#55]
Documentation on this page https://circleci.com/developer/orbs/orb/mathworks/matlab#commands-install is outdated. New features and their usage should be captured there.

**Comment by davidbuzinski** [comment]
Hi @yitingw3,

Thank you for the feedback. We are working on updating the doc for our orb, but cannot publish the new doc until we officially release v1. I will update this issue when the new doc is published.

Thanks,
David
