### ISSUE TITLE
circle CI run tests with parpool failed

### ISSUE THREAD

**Issue by adastar** [mathworks/matlab-circleci-orb#60]
I installed PCT when start MATLAB, when I run the test with parallel true mode, I see the following error:

Starting parallel pool (parpool) using the 'Processes' profile ...
Parallel pool using the 'Processes' profile is shutting down.

Error using gcp
Parallel pool failed to start with the following error. For more detailed
information, validate the profile 'Processes' in the Cluster Profile Manager.

Error in scriptgen.internal.scripts.TestScriptBuilder>canRunInParallel (line 214)
if isempty(gcp())

Error in scriptgen.internal.scripts.TestScriptBuilder/build (line 39)
                [canUseParallel, cannotUseParallelMsg] = canRunInParallel();

Error in scriptgen.CodeProvider/createCode (line 104)
            code = builder.build();

Error in scriptgen.CodeProvider/createScript (line 72)
            script = obj.createCode(obj.ScriptBuilderFactory, type, varargin{:});

Error in genscript (line 24)
script = provider.createScript(type, varargin{:});

Caused by:
    Error using
    parallel.internal.pool.AbstractInteractiveClient>iThrowWithCause
    Failed to initialize the interactive session.
        Error using
        parallel.internal.pool.AbstractInteractiveClient>iThrowIfBadParallelJobStatus
                The interactive communicating job failed with no message.
 
exit status 1

Exited with code exit status 1

**Comment by davidbuzinski** [comment]
Hi @adastar I have notified the relevant team internally. I will update this issue when it has been addressed.

Thanks,
David

**Comment by davidbuzinski** [comment]
Hi @adastar 

The issues with Parallel Computing Toolbox should be resolved now.

Thanks,
David
